[package]
name = "nexie-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_socketio = "0.6.0"
serde_json = "1.0"
tray-item = "0.10.0"
directories = "5.0"
tinyfiledialogs = "3.9"
dotenvy = "0.15.7"

[package.metadata.bundle]
name = "Nexie Gateway"
identifier = "com.nexie.gateway"
version = "1.0.0"
icon = ["assets/gateway_icon.png"]
copyright = "Copyright (c) Zaman Shaikh 2026. All rights reserved."
